[default]
Library=Polistil - Red/White borders
Scale=1:32
Unit=cm
Logo=polistil.jpg


[Straight]
Name=Straight R/W border
Shape=5.00,30.00
Texture1=f,255,255,255
Texture2=c,r,idb_red,,15,1,,,1.00,0,28.00,5.00
Notes=Fake red/white straight border - not a manufacturer part

[Half Straight]
Name=Straight R/W border
Shape=5.00,15.00
Texture1=f,255,255,255
Texture2=c,r,idb_red,,7,1,,,1.00,0,13.00,5.00
Notes=Fake red/white straight border - not a manufacturer part

[Quarter Straight]
Name=Straight R/W border
Shape=5.00,7.50
Texture1=f,255,255,255
Texture2=c,r,idb_red,,3,1,,,1.00,0,5.50,5.00
Notes=Fake red/white straight border - not a manufacturer part

[A14 Outer]
Name=A14 Outer R/W curve border
Shape=curve,51.50,-5.00,30.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,13,1,,,1.11,51.50,28.89,56.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A14 Inner]
Name=A14 Inner R/W curve border
Shape=curve,29.00,5.00,30.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,7,1,,,1.69,29.00,28.31,34.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A9 Outer]
Name=A9 Outer R/W curve border
Shape=curve,34.50,-5.00,60.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,17,1,,,1.66,34.50,58.34,39.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A9 Inner]
Name=A9 Inner R/W curve border
Shape=curve,12.00,5.00,60.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,7,1,,,3.37,12.00,56.63,17.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A49 Outer]
Name=A 49Outer R/W curve border
Shape=curve,26.00,-5.00,60.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,13,1,,,2.20,26.00,57.80,31.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A49 Inner]
Name=A49 Inner R/W curve border
Shape=curve,3.50,5.00,60.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,3,1,,,6.74,3.50,53.26,8.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A44 Outer]
Name=A44 Outer R/W curve border
Shape=curve,68.50,-5.00,15.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,7,1,,,0.84,68.50,14.16,73.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A44 Inner]
Name=A44 Inner R/W curve border
Shape=curve,46.00,5.00,15.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,5,1,,,1.12,46.00,13.88,51.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A43 Outer]
Name=Outer R/W curve border
Shape=curve,34.50,-5.00,30.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,9,1,,,1.66,34.50,28.34,39.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A43 Inner]
Name=A43 Inner R/W curve border
Shape=curve,12.00,5.00,30.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,3,1,,,3.37,12.00,26.63,17.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A231 Outer]
Name=A231 Outer R/W curve 5° border
Shape=curve,153.50,-5.00,5.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,5,1,,,0.37,153.50,4.63,158.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[A231 Inner]
Name=A231 Inner R/W curve 5° border
Shape=curve,131.00,5.00,5.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,5,1,,,0.42,131.00,4.58,136.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3110-Outer]
Name=Fleischmann F3110 Outer R/W curve border
Shape=curve,27.0,-5,90.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,21,1,,,2.08,27.0,87.92,32.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3110-Inner]
Name=Fleischmann F3110  Inner R/W curve border
Shape=curve,4.5,5.0,90.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,7,1,,,6.03,5.0,83.97,9.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3111 Outer]
Name=Fleischmann F3111 Outer R/W curve border
Shape=curve,45.0,-5,45.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,17,1,,,1.26,45.0,43.74,50.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3111 Inner]
Name=Fleischmann F3111 Inner R/W curve border
Shape=curve,22.50,5.0,45.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,9,1,,,2.08,23.50,42.92,27.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3112 Outer]
Name=Fleischmann F3112 Outer R/W curve border
Shape=curve,63.0,-5,45.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,23,1,,,0.90,63.00,44.10,68.00, 0.00
Notes=Fake red/white curve border - not a manufacturer part

[F3112 Inner]
Name=Fleischmann F3112 Inner R/W curve border
Shape=curve,40.50,5,45.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,17,1,,,1.26,40.50,43.74,45.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part


[RWCI_15]
Name=Inner R/W curve border
Shape=curve,20.50,5.00,60.00
Texture1=f,255,255,255
Texture2=c,c,idb_red,,13,1,,,2.25,20.50,57.75,25.50, 0.00
Notes=Fake red/white curve border - not a manufacturer part